### ISSUE TITLE
Drop the plugin. prefix from config

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-shipper-boshrelease#1]
I think we design the config as if this is a core BOSH feature (in the hope that we can make that happen)

Thus, rather than prefixing all properties with `plugin.log.`, I think they should just be `log.`

eg:

```
properties:
  ...snip...
  logs:
    syslog:
      server: "192.0.2.1:5514"
```
